DROP DATABASE IF EXISTS TG11;

CREATE DATABASE TG11;

USE TG11;

CREATE TABLE PARTIDA (
	ID INT NOT NULL,
	GANADOR VARCHAR(50),
	DURACION INT,
	FECHA DATETIME,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE JUGADOR (
	ID INT NOT NULL,
	NOMBRE VARCHAR(50),
	CONTRASENA VARCHAR(50),
	RECORD INT,
	FICHAS INT,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE PARTICIPACION (
	ID_P INT NOT NULL,
	ID_J INT NOT NULL,
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID),
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID)
)ENGINE=InnoDB;

INSERT INTO PARTIDA VALUES(1, 'ARNAU', 60, '21-01-13 16:05');
INSERT INTO PARTIDA VALUES(2, 'JOAN', 600, '20-11-23 12:34');
INSERT INTO PARTIDA VALUES(3, 'SERGI', 160, '20-09-24 17:30');

INSERT INTO JUGADOR VALUES(1, 'ARNAU', '123ABC', 1234, 700);
INSERT INTO JUGADOR VALUES(2, 'JOAN', 'ABC123', 2345,500);
INSERT INTO JUGADOR VALUES(3, 'SERGI', '456ASD', 789,300);

INSERT INTO PARTICIPACION VALUES(1, 1);
INSERT INTO PARTICIPACION VALUES(1, 2);
INSERT INTO PARTICIPACION VALUES(1, 3);
INSERT INTO PARTICIPACION VALUES(2, 1);
INSERT INTO PARTICIPACION VALUES(2, 2);
INSERT INTO PARTICIPACION VALUES(3, 1);
INSERT INTO PARTICIPACION VALUES(3, 3);
